In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../datasets/superstore_day1_practice_dirty.csv')
df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-198797,2024-10-06,2025-05-01,Second Class,CUST-4170,Ruben Ramirez,Home Office,South,Technology,Copiers,Virtual didactic synergy,2467.49,9,0.29,617.24
1,CA-233440,2023-06-12,2025-05-05,First Class,CUST-1196,Jesse Ortega,Home Office,Central,Furniture,Furnishings,Operative reciprocal projection,2751.66,1,0.09,922.14
2,CA-691533,2024-04-18,2025-04-24,Standard Class,CUST-2985,Kathryn Castro,Corporate,East,Furniture,Chairs,Multi-lateral incremental knowledge user,1199.66,9,0.03,220.44
3,CA-277218,2023-11-02,2025-05-07,First Class,CUST-2412,Sharon Taylor,Consumer,South,Office Supplies,Labels,Integrated bifurcated groupware,2335.57,6,0.30,620.16
4,CA-311967,2023-07-15,2025-04-14,First Class,CUST-3728,David Murillo,Corporate,South,Office Supplies,Binders,Re-contextualized human-resource benchmark,2540.88,5,0.03,258.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5000,CA-500487,2023-08-09,2025-04-10,Same Day,CUST-1395,Amanda Valencia,Home Office,Central,Technology,Accessories,Business-focused mobile Graphical User Interface,3804.78,6,0.36,544.72
5001,CA-331779,2025-01-11,2025-04-25,Same Day,CUST-7352,Jessica Anderson,Home Office,West,Furniture,Tables,Multi-tiered directional data-warehouse,2963.61,2,0.29,623.88
5002,CA-967024,2023-07-13,2025-04-22,First Class,CUST-9193,Paul Park,Corporate,East,Furniture,Furnishings,Sharable radical info-mediaries,2950.27,6,0.25,671.53
5003,CA-412796,2024-11-17,2025-04-24,Same Day,CUST-4047,Ann Orr,Home Office,South,Office Supplies,Labels,Profound responsive knowledgebase,2764.98,8,0.27,97.81
5004,CA-395029,2024-01-19,2025-04-12,Second Class,CUST-2438,Allen Brewer,Corporate,West,Technology,Phones,Balanced client-driven groupware,2126.31,6,0.40,-56.13

In [3]:
df['Region'].value_counts(dropna=False)

Region
South          1288
West           1252
Central        1245
East           1214
south             3
West Region       3
Name: count, dtype: int64

In [4]:
df['Region'].value_counts(normalize=True,dropna=False)

Region
South          0.257343
West           0.250150
Central        0.248751
East           0.242557
south          0.000599
West Region    0.000599
Name: proportion, dtype: float64

In [5]:
df.shape

(5005, 15)

In [6]:
df.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Region', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [7]:
df.dtypes

Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Region            object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [8]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-198797,2024-10-06,2025-05-01,Second Class,CUST-4170,Ruben Ramirez,Home Office,South,Technology,Copiers,Virtual didactic synergy,2467.49,9,0.29,617.24
1,CA-233440,2023-06-12,2025-05-05,First Class,CUST-1196,Jesse Ortega,Home Office,Central,Furniture,Furnishings,Operative reciprocal projection,2751.66,1,0.09,922.14
2,CA-691533,2024-04-18,2025-04-24,Standard Class,CUST-2985,Kathryn Castro,Corporate,East,Furniture,Chairs,Multi-lateral incremental knowledge user,1199.66,9,0.03,220.44
3,CA-277218,2023-11-02,2025-05-07,First Class,CUST-2412,Sharon Taylor,Consumer,South,Office Supplies,Labels,Integrated bifurcated groupware,2335.57,6,0.30,620.16
4,CA-311967,2023-07-15,2025-04-14,First Class,CUST-3728,David Murillo,Corporate,South,Office Supplies,Binders,Re-contextualized human-resource benchmark,2540.88,5,0.03,258.06

array(['2024-10-06', '2023-06-12', '2024-04-18', ..., '2023-07-13',
       '2024-11-17', '2024-01-19'], dtype=object)

In [13]:
for col in df.columns:
    if df[col].isnull().any():
        print(f"{col} has missing values")
        print(df[col].isnull().sum())

Category has missing values
3
Sales has missing values
5
Profit has missing values
5

In [21]:
df_Fill = df.fillna(value=df['Profit'].median())
df_Fill['Profit'].isnull().any()
df_Fill[df['Profit'].isnull()]

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
1655,CA-941961,2023-10-18,2025-04-29,Second Class,CUST-6435,Olivia Howell,Consumer,Central,Office Supplies,Binders,Innovative coherent process improvement,2505.01,7,0.11,444.695
3017,CA-287357,2024-10-02,2025-04-26,Same Day,CUST-5881,Sarah Kennedy,Consumer,South,Furniture,Bookcases,Self-enabling national neural-net,1694.57,8,0.17,444.695
3234,CA-973010,2024-10-17,2025-04-29,First Class,CUST-5466,Connie Wilson,Consumer,South,Office Supplies,Storage,Re-contextualized 5thgeneration access,3178.41,5,0.19,444.695
3236,CA-186803,2023-11-03,2025-04-25,Second Class,CUST-9778,Victor Clements,Consumer,Central,Technology,Copiers,Right-sized 3rdgeneration success,71.83,5,0.18,444.695
3310,CA-644017,2024-06-08,2025-05-04,Second Class,CUST-3143,Kevin Reyes,Corporate,East,Technology,Accessories,Persistent scalable archive,239.57,2,0.15,444.695

In [35]:
df_Fill = df.fillna(value=f"{df['Category'].mode().to_string()}")
df_Fill[df['Category'].isnull()]

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
1558,CA-541371,2024-04-14,2025-04-09,Second Class,CUST-2804,Stacey Hamilton,Home Office,West,0 Furniture,Tables,Upgradable incremental archive,4199.88,1,0.46,843.97
1812,CA-703499,2025-03-24,2025-04-13,Same Day,CUST-5675,Laura Butler,Corporate,Central,0 Furniture,Copiers,Mandatory holistic encryption,2831.52,10,0.25,310.77
3875,CA-463513,2023-05-20,2025-04-10,Standard Class,CUST-8737,Tammy Rodriguez,Home Office,West,0 Furniture,Art,Secured multimedia methodology,710.15,3,0.39,666.11

In [38]:
df_Fill = df['Sales'].dropna(how='any')
df_Fill[df['Sales'].isna()]

Series([], Name: Sales, dtype: float64)

In [40]:
df[df.duplicated()]

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Region,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
5000,CA-500487,2023-08-09,2025-04-10,Same Day,CUST-1395,Amanda Valencia,Home Office,Central,Technology,Accessories,Business-focused mobile Graphical User Interface,3804.78,6,0.36,544.72
5001,CA-331779,2025-01-11,2025-04-25,Same Day,CUST-7352,Jessica Anderson,Home Office,West,Furniture,Tables,Multi-tiered directional data-warehouse,2963.61,2,0.29,623.88
5002,CA-967024,2023-07-13,2025-04-22,First Class,CUST-9193,Paul Park,Corporate,East,Furniture,Furnishings,Sharable radical info-mediaries,2950.27,6,0.25,671.53
5003,CA-412796,2024-11-17,2025-04-24,Same Day,CUST-4047,Ann Orr,Home Office,South,Office Supplies,Labels,Profound responsive knowledgebase,2764.98,8,0.27,97.81
5004,CA-395029,2024-01-19,2025-04-12,Second Class,CUST-2438,Allen Brewer,Corporate,West,Technology,Phones,Balanced client-driven groupware,2126.31,6,0.40,-56.13

In [43]:
df_Fill = df.drop_duplicates()
df_Fill.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       5000 non-null   object
 1   Order Date     5000 non-null   object
 2   Ship Date      5000 non-null   object
 3   Ship Mode      5000 non-null   object
 4   Customer ID    5000 non-null   object
 5   Customer Name  5000 non-null   object
 6   Segment        5000 non-null   object
 7   Region         5000 non-null   object
 8   Category       4997 non-null   object
 9   Sub-Category   5000 non-null   object
 10  Product Name   5000 non-null   object
 11  Sales          4995 non-null   float64
 12  Quantity       5000 non-null   int64
 13  Discount       5000 non-null   float64
 14  Profit         4995 non-null   float64
dtypes: float64(3), int64(1), object(11)
memory usage: 625.0+ KB

In [52]:
df_Fill.fillna(value=df_Fill['Profit'].median(),inplace=True)
df_Fill.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       5000 non-null   object
 1   Order Date     5000 non-null   object
 2   Ship Date      5000 non-null   object
 3   Ship Mode      5000 non-null   object
 4   Customer ID    5000 non-null   object
 5   Customer Name  5000 non-null   object
 6   Segment        5000 non-null   object
 7   Region         5000 non-null   object
 8   Category       5000 non-null   object
 9   Sub-Category   5000 non-null   object
 10  Product Name   5000 non-null   object
 11  Sales          5000 non-null   float64
 12  Quantity       5000 non-null   int64
 13  Discount       5000 non-null   float64
 14  Profit         0 non-null      float64
dtypes: float64(3), int64(1), object(11)
memory usage: 625.0+ KB

C:\Users\tejva\AppData\Local\Temp\ipykernel_21116\1477548868.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Fill.fillna(value=df_Fill['Profit'].median(),inplace=True)